@Assignment8_HostAddress = http://localhost:5260

GET {{Assignment8_HostAddress}}/movies
accept: application/json

###
//Works

GET {{Assignment8_HostAddress}}/movie/8
accept: application/json

###
//works   


POST {{Assignment8_HostAddress}}/movie
accept: application/json

###
//400 bad request
//Unhandled exception

# fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
#       An unhandled exception has occurred while executing the request.
#       Microsoft.AspNetCore.Http.BadHttpRequestException: Implicit body inferred for parameter "movie" but no body was provided. Did you mean to use a Service instead?

DELETE {{Assignment8_HostAddress}}/movie/26
accept: application/json

###
// 500 internal server error
//DID delete movie


PUT {{Assignment8_HostAddress}}/movie/28
accept: application/json

###
//400 bad request

# fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
#       An unhandled exception has occurred while executing the request.
#       Microsoft.AspNetCore.Http.BadHttpRequestException: Implicit body inferred for parameter "updatedMovie" but no body was provided. Did you mean to use a Service instead?
