@Assignment8_HostAddress = http://localhost:5260

GET {{Assignment8_HostAddress}}/movies
accept: application/json

###
//Works

GET {{Assignment8_HostAddress}}/movie/8
accept: application/json

###
//works   


POST {{Assignment8_HostAddress}}/movie
content-Type: application/json
{
  "Title": "Five Nights at Freddy's",
  "ReleaseDate": "2015-07-12"
  "Genre": "Horror",
  "Price": 9.99,
  "Rank": 5,
  "Image":
}

###
//400 bad request
//Unhandled exception

# fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
#       An unhandled exception has occurred while executing the request.
#       Microsoft.AspNetCore.Http.BadHttpRequestException: Implicit body inferred for parameter "movie" but no body was provided. Did you mean to use a Service instead?

DELETE {{Assignment8_HostAddress}}/movie/30
accept: application/json

###
//Works


PUT {{Assignment8_HostAddress}}/movie/34
content-Type: application/json
{
  "Id": 34",
  "Title": "Superman",
  "ReleaseDate": "2025-03-04",
  "Genre": "Comedy",
  "Price": 14.99,
  "Rank": 2,
  "Image": 



###



//400 bad request

# fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
#       An unhandled exception has occurred while executing the request.
#       Microsoft.AspNetCore.Http.BadHttpRequestException: Implicit body inferred for parameter "updatedMovie" but no body was provided. Did you mean to use a Service instead?
