@Assignment8_HostAddress = http://localhost:5260

GET {{Assignment8_HostAddress}}/movies
accept: application/json

###
//500 internal server error
//Db context error

# fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
#       An error occurred using the connection to database '' on server ''.
# fail: Microsoft.EntityFrameworkCore.Query[10100]
#       An exception occurred while iterating over the results of a query for context type 'Assignment8.Data.RazorPagesMovieContext'.

GET {{Assignment8_HostAddress}}/movie/3
accept: application/json

###
//500 internal server error
//DB context error
# fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
#       An error occurred using the connection to database '' on server ''.
# fail: Microsoft.EntityFrameworkCore.Query[10100]
#       An exception occurred while iterating over the results of a query for context type 'Assignment8.Data.RazorPagesMovieContext'.

POST {{Assignment8_HostAddress}}/movie
accept: application/json

###
//400 bad request
//Unhandled exception

# fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
#       An unhandled exception has occurred while executing the request.
#       Microsoft.AspNetCore.Http.BadHttpRequestException: Implicit body inferred for parameter "movie" but no body was provided. Did you mean to use a Service instead?

DELETE {{Assignment8_HostAddress}}/movie/1
accept: application/json

###
//500 internal server error

# fail: Microsoft.EntityFrameworkCore.Database.Connection[20004]
#       An error occurred using the connection to database '' on server ''.
# fail: Microsoft.EntityFrameworkCore.Query[10100]
#       An exception occurred while iterating over the results of a query for context type 'Assignment8.Data.RazorPagesMovieContext'.

PUT {{Assignment8_HostAddress}}/movie/4
accept: application/json

###
//400 bad request

# fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
#       An unhandled exception has occurred while executing the request.
#       Microsoft.AspNetCore.Http.BadHttpRequestException: Implicit body inferred for parameter "updatedMovie" but no body was provided. Did you mean to use a Service instead?
